language: minimal

dist: bionic

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - WIRESHARK_BRANCH=master-3.2 PLUGIN_DIR=$TRAVIS_BUILD_DIR BUILD_STANDALONE=no
  - WIRESHARK_BRANCH=master-3.2 PLUGIN_DIR=$TRAVIS_BUILD_DIR BUILD_STANDALONE=yes

jobs:
  exclude:
    # Exclude gcc build on OSX
    - os: osx
      compiler: gcc
    # Exclude standalone build on OSX
    - os: osx
      env: WIRESHARK_BRANCH=master-3.2 PLUGIN_DIR=$TRAVIS_BUILD_DIR BUILD_STANDALONE=yes

before_install:
  - echo $TRAVIS_OS_NAME

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        ${PLUGIN_DIR}/tools/osx-provision-source.sh;
        PATH=/usr/local/opt/qt5/bin:$PATH;
    fi

  # See https://github.com/travis-ci/travis-ci/issues/5326
  #- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ ${BUILD_STANDALONE} == "no" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-provision-source.sh;
    fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ ${BUILD_STANDALONE} == "yes" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-provision-standalone.sh;
    fi

install:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-build-source.sh;
        export PATH=${PATH}:${HOME}/wireshark-${WIRESHARK_BRANCH}/build/run;
        export WIRESHARK_RUN_FROM_BUILD_DIRECTORY=1;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        ${PLUGIN_DIR}/tools/ubuntu-build-standalone.sh;
    fi

script:
  - python ${PLUGIN_DIR}/tests/__init__.py

before_deploy:
  - if [ ${BUILD_STANDALONE} == "no" ]; then
        cp build/run/plugins/3.2/epan/sap.so build/sap-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x86-64.so;
    fi
  - if [ ${BUILD_STANDALONE} == "yes" ]; then
        mv build/sap.so build/sap-${TRAVIS_TAG}-${TRAVIS_OS_NAME}-x86-64.so;
    fi

deploy:
    provider: releases
    token:
        secure: "R+nmMCuHexC7Y7dZedEQ3mF2SE1kkfeazWHXtmWZFZF+v9wrtp+Er5SAKzvdf7NFpzj6ecF99f/Fpy6LLfdSmfQGzTiU9BRBodkx4ezEDEc0VVyS9V2I+UAYisenXfj7EtmX5N33tlj2ujogPt+RH0abrRmD1mxBqzzybPd7q6o="
    file: "build/*.so"
    file_glob: true
    on:
        tags: true
        repo: SecureAuthCorp/SAP-Dissection-plug-in-for-Wireshark
        condition: "${BUILD_STANDALONE} == \"yes\" || ${TRAVIS_OS_NAME} == \"osx\""
